# Generated by ChatGPT on 2025-11-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_percent',
            field=models.FloatField(default=0, verbose_name='Фоизи муассиса'),
        ),
    ]
