# Generated by Django 5.2.7 on 2025-11-03 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('invoice_code', models.IntegerField()),
                ('amount_total', models.FloatField()),
                ('maorif_percent', models.FloatField()),
                ('institution_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='book.bookloan')),
            ],
        ),
    ]
