# Generated by Django 5.2.7 on 2026-01-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пардохт', 'verbose_name_plural': 'Пардохтҳо'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_code',
            field=models.BigIntegerField(),
        ),
    ]
