# Generated by Django 5.2.7 on 2026-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpricefactor',
            options={'ordering': ['-factor', 'label'], 'verbose_name': 'Фоизнокии иҷораи китоб', 'verbose_name_plural': 'Фоизнокии иҷораи китоб'},
        ),
        migrations.AddField(
            model_name='bookpricefactor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Шарҳу эзоҳ'),
        ),
        migrations.AlterField(
            model_name='bookpricefactor',
            name='factor',
            field=models.FloatField(verbose_name='Фоиз аз нархи китоб'),
        ),
        migrations.AlterField(
            model_name='bookpricefactor',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Номгу'),
        ),
    ]
