# Generated by ChatGPT on 2025-11-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpricefactor',
            name='price_from',
            field=models.FloatField(blank=True, null=True, verbose_name='Нарх аз'),
        ),
        migrations.AddField(
            model_name='bookpricefactor',
            name='price_to',
            field=models.FloatField(blank=True, null=True, verbose_name='Нарх то'),
        ),
        migrations.AddField(
            model_name='bookpricefactor',
            name='year_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Соли нашр аз'),
        ),
        migrations.AddField(
            model_name='bookpricefactor',
            name='year_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Соли нашр то'),
        ),
        migrations.AddField(
            model_name='bookpricefactor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Шарҳу эзоҳ'),
        ),
    ]
